name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 4.0.8
homepage: https://github.com/justkawal/excel
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: 
  xml: 
  collection: 
  equatable: 

dev_dependencies:
  test: 
  lints: 
